label carlb:

"I'm like a rag doll being yanked back before being thrown to the side."
"I go stumbling away with several yelps, each one in sync with the steps I take on my swollen ankle."
"I finally go down as gently as I can, on my hands and knees as the pain almost blinds me."
"The sound of quick footsteps in gravel along with a loud laugh has me raising my head back up to see what's going on."
"Through the tears, I see Carl dancing around, dodging back and forth as Jenna swipes at him with the knife."
"The laughing is coming from Carl as he leaps out of the way with a nimbleness I've never seen him have."
c "\"Whoops! Almost had me there!\""
"Carl easily ducks around another slash from the fox."
"Jenna, on the other hand, isn't saying anything."
"Instead, her eyes are locked on Carl, teeth grit with what looks like foam gathering at the corners of her mouth."
"I suddenly comprehend what I'm seeing; one of my friends trying to kill the other."
m "\"Jenna...Jenna, stop!\""
"I push myself unsteadily to my feet, trying to limp after them."
"But it's not much use; they're both moving so fast away from me, around me, as they continue their little dance."
"Even Raven seems too shocked to move; backing away as the two fight past him."
m "\"Carl! Jenna!\""
"I look around for something, anything to get this to stop, but Jenna seems hell-bent on stabbing Carl."
c "\"You were always a terrible fighter, you know that?\""
"Carl dodges to the side again and snatches up the wrist of the paw that's holding the knife."
play sound "thud.ogg"
with vpunch
"In one swift movement, Carl uses his other hand to punch Jenna across the face, sending the fox to the ground in a heap."
"The cracking sound it makes causes fur to stand up all over my body and I limp towards Jenna."
m "\"Guys, that's enough!\""
"I'm looking for the knife, I just want to get it away from Jenna before she can hurt anyone else, or herself."
"But Carl is already standing next to her, and he bends down to pick up a rock."
"It's about the size of a softball, and it has a pointy end on it."
"He points that end down, and raises it over Jenna."
m "\"Carl!\""
"I lunge at the ram and tackle him around the waist."
"He must have been completely focused on Jenna because I'm able to knock him over pretty easily."
"He makes an \"Oomph\" sound above me before we crash into the ground."
m "\"What the fuck are you doing!?\""
"I push myself up over the ram, reaching above us to try to pry the rock from his hand."
"Desperately, I look behind me."
m "\"Raven! Get...get Jenna, get her away somewhere!\""
ra "\"Um!\""
"Raven's standing there, pulling at his ears as he stares at the fox on the ground."
m "\"Help her!\""
"I look back down at Carl, and he's staring right back at me, breathing hard."
m "\"Carl?\""
"I call his name, not only to get a response, but also because I'm not sure that's who I'm talking to."
"He doesn't say anything and just goes on staring at me, but he does let go of the rock and it rolls gently from his hand to the desert floor."
m "\"Carl let's go back inside, okay?\""
stop music fadeout 5.0
"I use a delicate tone, feeling like I'm talking to some unhinged stranger."
"Carl stares at me a moment longer, then lets out a soft huff through his nose with a half-laugh."
c "\"Yeah, sure.\""
m "\"You're done right?\""
c "\"Yes.\""
m "\"So I'm going to let you up and we're going back to your house, okay?\""
c "\"Yep.\""
"Slowly, I get up, standing in the way of Jenna in case Carl goes for her."
"I look back at Raven."
m "\"Pick up the knife, throw it into the desert, or something.\""
"I lower my voice stepping back a bit so I can lean toward the husky even though I feel Carl's eyes are on me."
m "\"Take her down to the basement and I'll take Carl upstairs...we'll figure something out later, okay?\""
ra "\"O—okay.\""
"I turn back to Carl, then reach my hand out toward him."
m "\"Dude, my ankle is so fucked. Can you help me back up to the bedroom.\""
c "\"Hm.\""
"Carl lets out a grunt then another half-laugh snort."
c "\"Sure.\""
"He reaches out to me, eyes glancing down at the crumpled fox as he does."
"I can hear Jenna stirring a bit, so I gently push into Carl to hurry our trek back to the mansion."
"I glance back a few times, the last time I see Raven crouched over Jenna, mouth moving as he talks to her."

scene bg carlsparentsroom with fade
play loop "roomtone.ogg" fadein 3.0
"As soon as we enter Carl's parents' bedroom, the ram leaves me to stand next to the bed."
c "\"You going to sleep?\""
"Carl turns away from me and starts to walk around the room, looking at the walls, the lights, even under the bed."
m "\"Maybe...I'm not really tired though."
"Instead of sitting on the bed, I limp toward the balcony to look out the glass doors."
"I just barely catch of a glimpse of Jenna and Raven moving toward the mansion, Jenna leaning on the husky for support."
"I watch them disappear underneath the balcony."
m "\"Carl...I don't know what we're gonna do.\""
c "\"Hm.\""
"I turn to look at him."
m "\"Were you really going to hit her with the rock?\""
"Carl pauses, glancing at me."
c "\"...No, I was gonna hit her arms, make it harder for her to go after us again.\""
"I frown since I can't really remember if it looked that way."
"He seemed to point it right towards her head."
"Either way it's fucked, thinking about having to \"incapacitate\" one of my best friends."
"Carl starts to open the drawers in the dresser before slamming them shut with a loud snap."
m "\"Are you looking for something?\""
"Carl doesn't answer, instead pulling the drawers completely out of the dresser instead."
m "\"Carl.\""
c "\"Hm?\""
m "\"What are you doing?\""
"More silence."
m "\"Carl!\""
show Carlalt2 Annoyed at center with dissolve
c "\"What!?\""
"Carl snaps at me."
"I shrink back for a moment, then glare."
m "\"Don't yell at me. What happened out there?\""
"Carl turns back to the dresser, sticking his head inside the opening where a drawer once was."
"His horns clack around against the wood."
c "\"He tried to stab me. What else is there to know?\""
"I sigh, looking down at my ankle."
"I'm startled at how swollen it is now, unrecognizable."
"I wonder if a sprain can be bad enough that it needs to be amputated."
"I try not to think about it and move to the bed, sitting down gingerly."
"Carl makes his way over to the bedside table next to me."
m "\"I'm talking about the way you were acting, how you were laughing and stuff.\""
"Carl shrugs his shoulders, made vague by the way he seems to be wrestling the table out of its corner, looking behind it."
c "\"The whole thing's ridiculous, isn't it? Gotta lighten the mood with humor, sometimes.\""
m "\"While she's trying to stab you?\""
"Another shock at remembering the attempted murder, though it's duller."
"Carl yanks the drawer from the table violently."
m "\"What are you doing?\""
c "\"Looking for bullshit notes. That's why we're here, isn't it?\""
show Carlalt2 Neutral with dis
"I reach out and grab Carl's arm at which he freezes and finally looks at me."
"I swallow, trying to think of how to phrase this."
m "\"Carl are you...you, anymore?\""
c "\"Of course I'm me.\""
"The ram pulls his arm away from my grasp."
"I shake my head."
m "\"We know Jenna isn't, I guess in a weird fucked up way she was gonna snap eventually but—\""
"Carl keeps rummaging around and I wonder if he's listening at all."
m "\"—And I could sort of tell you weren't either, but now I'm just having trouble seeing you at all anymore.\""
"Carl finally sets the drawer down, looking around the room."
"He wipes his hands off on his shorts, then slowly moves closer before sitting down next to me on the bed."
c "\"I'm still me...we're all just under a lot of pressure right now, you know...dude?\""
m "\"I guess?\""
"It's strange."
"It's like he's someone who's trying to pretend to be Carl."
"That idea puts me on edge."
"I look away, thinking back on the attack."
m "\"That newspaper clipping...it makes sense why that would set John off, right?\""
show Carlalt2 Annoyed with dis
"Carl snorts."
c "\"I'm not surprised.\""
m "\"I told you earlier they want us to see the truth before we can leave...but wasn't that the truth?\""
show Carlalt2 Neutral with dis
"Carl doesn't say anything."
"I shake my head."
m "\"Unless it's not...I don't know.\""
"Carl remains silent."
"Guess it was stupid to think James would help me."
"At this point I'm equally suspicious of the two of them."
"I lay back on the bed, rubbing my eyes."
"I'd thought that letting James help us would lead us to the way out of here, but now..."
"It feels as if I've just lost a friend."
"Carl's hand suddenly comes to rest on my shoulder."
c "\"You just upset that we didn't get to go all the way earlier?\""
m "\"Huh?\""
"I furrow my brow."
"That's the furthest thing from my mind right now."
show Carlalt2 Teasing with dis
"But the ram turns to me on the bed, a coy smile on his face."
m "\"What are you talking about?\""
"Carl rolls over on the bed, to the other side then reaches out to rub my arm again."
m "\"What are you doing?\""
"I watch him rubbing through the fur on my arm."
c "\"Picking up where we left off.\""
"Carl runs his hand up under my shirt before pushing the fabric up to expose my torso."
"I can't help but react to the touch."
"Despite what just happened not 20 minutes ago, despite the way Carl's acting...despite that it's not Carl."
"...Or is it? Something seems a bit more familiar about him now."
"My urges are made all the worse as the ram runs his hand down my chest, toward the waistband of my pants."
m "\"I don't know if this is a good idea right now.\""
"I reach up to push my shirt back down."
c "\"You sure? Not even a hand job?\""
"Carl pauses with his hand on my stomach, gently moving his fingers around in the fur."
"The bulge in my pants is obvious."
m "\"We should be thinking of a way to escape.\""
"Still, I stare at the hand on my body."
c "\"Well, we're not going anywhere in the meantime. Besides, didn't we come here to rest? Might as well get one out while you can.\""
"I take back what I said about familiarity."
"Carl's unusually confident, weirdly seductive, and it has my heart beating fast."
c "\"Might help you get to sleep.\""
play music "heartbeat.ogg"
hide Carlalt2 with dissolve
"Something feels strange in the room, a low, surreal drone that makes it feel as if I'm in a dream."
"My movements feel numb, like they're not my own, my urges are not my own."
"It feels old and overpowering, this feeling, and Carl seems to be radiating it."
"At this point I don't really know what's normal, or okay, or basically what reality is anymore."
"But I do know that my body wants this."
m "\"Maybe...maybe real quick.\""
"Carl presses his lips to the side of my face, then lower toward my neck."
"At the same time, his hand goes back to my shirt that I've lowered to the top of my stomach and pushes it all the way up, over my face."
"With just a moment of hesitation I raise my arms up so he can completely get rid of the shirt."
"Carl pauses, looking over my torso again."
c "\"You're in shape.\""
"I don't say anything."
"The way he's scanning his eyes over my body makes my heart skip a beat."
"I look toward the door, wondering if maybe I should check if there's a lock."
"Not only because Raven coming in and seeing what we're up to at a time like this would be bad—"
"But also because Jenna seeing this, in the state of mind she's in, would be a disaster."
"How fucking immature am I that I'm doing this right now?"
m "\"Carl...I don't know if this is a good idea right now. What if Raven or—\""
c "\"What? You know Raven snuck off in the cabin to beat one out? You deserve this.\""
"I blush."
c "\"I'm just helping you out.\""
"I sigh and don't say anything as Carl starts kissing my neck, causing my cock to twitch a bit."
"Carl chuckles into my fur, making me shiver."
c "\"Pull your pants down and I'll help you out.\""
"Fuck it."
"I reach down and shove my pants and boxers down to my thighs, exposing my length to the cool air."
"A musky smell reaches my nose and I blush at the thought of Carl smelling it."
"I didn't exactly have much time to bathe over the past day or two."
"The ram doesn't seem to mind as his hand immediately goes to my cock, grabbing it up into his huge hand."
"It envelopes almost the entire thing and I gasp out in surprise, almost groaning at how sensitive I am."
c "\"Heh, you are pent up, huh?\""
"He gives me a squeeze before pumping a few times."
"Deep slow ones that push my ass and balls into the bed before I practically arch out into the upstroke."
"I gasp again, my eyes wide."
"I've never felt this much pleasure from just a hand job before."
"Carl laughs again at my expression."
c "\"Little sensitive? Here.\""
"Carl pushes me over onto my side, moving closer to spoon me as he continues to stroke my length."
"I try to keep quiet, gasping softly with every pump."
"I've never been jerked off like this."
"With each downstroke, the ram presses his crotch into my rear, forcing me into his hand."
"I can feel his own length against me, especially once he pushes my tail out the way."
"His free hand goes to my rear, and for a moment I worry he's going to go in with a finger."
m "\"Wait, I...I don't wanna do that.\""
"Carl nibbles my ear."
c "\"Alright.\""
"His hand instead feels up my ass, squeezing gently before sliding under me to come up around my chest."
"He gives me another enthusiastic stroke, squeezing my balls against my thighs before squeezing up."
"And just like that, that sends me over the edge."
"I lasted barely even a minute."
"I tense and stifle a whimper as I start to buck my hips into Carl's hand."
"Sensing this, Carl speeds up the pace and soon I'm trying not to let out otter squeaks as I writhe against the ram."
"Carl squeezes me tight, nibbling my ear before suddenly biting it hard."
"I wince in pain, chills going up and down my spine as the ram aims my spurts over the side of the bed."
"I spasm over and over until finally I slump down against the bed, gasping for breath."
"Carl chuckles again, giving me a few more strokes that send me into another spasm."
m "\"S—stop!\""
"I nudge his hand away before the ram finally pulls it back."
stop music fadeout 5.0
"I open my eyes and see that not too much has gotten on the bed."
"There are several white streaks glistening on the hardwood floor below, though."
"I rub my ear wincing."
m "\"What was that?\""
c "\"You came.\""
"Carl is sitting up now, dumping one of the several pillows behind us from their pillowcase."
m "\"You bit my ear.\""
"I pull my hand away to see that it's not bleeding, somehow."
"Carl shrugs."
c "\"Oh yeah, some people like that...guess you don't?\""
m "\"No.\""
"I frown at how nonchalant the ram is."
m "\"I mean, it was really hard.\""
"Carl wipes his hand off on the pillowcase, then tosses it over to me."
c "\"Sorry, I won't do it next time.\""
"Next time."
"I take the pillowcase and rub my dick with it, along with the little bit that got on the covers."
c "\"Alright, I'm tired. I'm gonna lay down, too.\""
"I'm a little put off."
"Instead of the primal urges I'd felt before, I feel empty, almost guilty at the thought of what we'd just done."
"I'm reminded that Jenna and raven are just a few floors below us."
"I should honestly go down and see how they're doing, but I can't really do that with Carl here."
"I look over my shoulder and see Carl laying on his back, eyes closed."
"He might already be asleep before I've even pulled my pants up."
"It's a bit odd that he's not trying to spoon me again like last time."
"I guess it's fine since I'm not really in the mood to be spooned."
"I give my dick a few wipes before I drop the pillowcase onto the floor next to the mess that's already there."
"I pull up my pants, wanting to take a shower, but too exhausted to check the bathroom for running water."
"I lay on my side, idly wondering if maybe I should go downstairs since Carl seems to be asleep, but..."
stop loop fadeout 3.0

scene bg black with slow_dissolve
play sound "cackle.ogg"
unk "\"Hehehe...\""
play music "drag.ogg" fadein 5.0
"A familiar cackle far in the distance pulls me out of my sleep."
"I open my eyes to a dark room, seeing the faint outline of the doorway."
"Is it nighttime...does time move in this place?"
"I sit up in the bed, looking around."
"It's dark, but I can see the outlines of the dresser and the bedside table, along with the empty bed I'm in."
"Where's Carl?"
"I swing my legs off the bed and feel lush, fuzzy carpet."
"My heart leaps in my chest."
"Am I back?"
"I don't want to get my hopes up because of what happened last time, but this place looks exactly like Carl's parents' room."
"I reach out to the lamp next to me to feel around for a switch, but it illuminates the moment I touch it."
scene bg carlsparentsroomnight
"And that's when I see the outline of a small person in the hall."
"I jump, eyes staring out into the dark hallway."
"A small fox stares back."
"I have enough time to see the overalls, a white shirt, before suddenly he turns and vanishes into the dark."
"I hear the patter of his footsteps down the hall, then down the stairs before it fades off into silence."
"I'm backed up against the headboard, heart hammering in my chest, staring at the dark rectangle."
"Quickly glancing around the room again, I don't see Carl anywhere."
"Slowly, I push myself out of the bed and pad around the room, keeping an eye on the door in case the fox came back."
"I glance out the glass doors as I pass them, to the dark balcony."
"I can't see anything, though I do see specks of light down in the town."
"From what I can see it looks normal as well."
"Swallowing loudly, I move toward the hallway."
"Something seems to be pushing me forward, toward the darkness."
"I look into the hallway, down toward the stairs, but it's completely black."
"Moving my hand up and down along the wall for a light switch, I hit one and am almost blinded by the bright light that shines down on me."
"I shield my eyes as I force myself to watch the stairs, but again I see nothing."
"Swallowing again, I force myself forward, toward the stairs and finally down the stairs."
"I try not to blink, eyes wide, watching for the little fox."
"I don't have my hopes up that this is real anymore."
"After seeing the fox boy, I know I'm still not in reality, at least not all the way."
"Well...maybe I am back, but those things from the other side have crossed over a bit and that's what I saw?"
scene bg kitchennight with dissolve
"I'm in the kitchen when I suddenly see a set of horns in the darkness, moving toward the stairs before they disappear."
m "\"Carl?\""
"I hurry toward the stairs, feeling again along the walls for a light switch."
"I hear clopping at the bottom, along with voice, small child-like voices."
"Stumbling down the stairs, I call out again."
m "\"Carl? Jenna? Raven?\""
"I start to wonder if I've left the other three somehow."
"Am I alone here?"
"Did we get separated?"
scene bg basement with dissolve
"Soon I'm running through the basement hall, toward the sound of voices."
"I'm at the door to the crawlspace, and without hesitation I unlatch the door and throw it open—"
"To find that same small fox."
"I see now that he's just a boy, maybe eight or nine years old in old-fashioned clothes."
"He stares at me, stoic and unmoving."
stop music fadeout 5.0
"I stare back in silence, then I see something."
"Two towering horns materialize above the boy and I see Carl's face."
"And then arms close around the fox's throat and the boy opens his mouth to scream."

scene bg carlsparentsroom
"I jolt awake on Carl's parents' bed."
"I'm back, it's bright again, and I look around to see the hardwood floor, the bunched up pillowcase on the bedside table."
"But Carl's not there, and there's still screaming."
play music "anger.ogg"
ra "\"Help! Stop!\""
"The sound is distant, coming from downstairs."
"My body is filled with adrenaline, both from the dream and from the screaming that I suddenly realize is very real."
"I jump off the bed and immediately go down to my knees as my ankle screams in agony."
"I have no choice though, and I force myself to my feet, half hopping, half limping my way to and through the hallway."
"It's easier now that I've got walls and rails I can half-support myself on."
"My heart thuds in my chest."
"I'm still bleary and confused from being asleep just thirty seconds ago."
"What I do know is that I have to help Raven and probably Jenna too."
"I don't have time to dwell on the realization that I've made a stupid mistake going to sleep, not keeping an eye on Carl."
ra "\"No! NO! NO!\""
scene bg kitchen with dissolve
"Stumbling through the kitchen, I hear the screams coming from down the flight of stairs to the basement before being cut off suddenly."
"I feel my heart sink as I limp and jump to the stairs, practically falling down the stairs to the basement below."
scene bg basement with dissolve
"I squint down the hall, unable to see clearly in the darkness."
"What I do get is a vague sense of movement in the dark, to the left."
"I move blindly in that direction, not sure what I'm going to find, or what I'm going to do."
m "\"Carl?\""
"I feel along the wall, then I feel nothing as I find a doorway."
"Reaching out for a light switch, I flip it on, and see that I'm in the weight room."
scene bg weightroom with dissolve
"And there's blood on the floor."
"I stare around in horror at the three big splotches and as I stare at them I think I even see them spreading."
"I go down to my knees, not even feeling my ankle at this point."
"I stare hard at the floor, looking around, but not seeing anyone."
m "\"Jenna? Raven?\""
"I call out their names in a hushed whisper."
"Footsteps."
stop music
play sound "thud.ogg"
with vpunch
"I'm hit harder than I've ever been in my life."
"The cold concrete of the ground meets my face as my limbs go out from underneath me."

scene bg mineshaft with slow_dissolve
play loop "floodlight.ogg" fadein 5.0
play music "whispers.ogg" fadein 10.0
"The feeling of rough, dirty ground against my face makes me crinkle my nose."
"I try to reach up and brush at it, but my hands don't come up."
"My shoulders ache horribly, and so do my knees."
"Not to mention my ankle, though that almost feels numb at this point."
"I slowly crack open my eyes, seeing nothing but dirt."
"Something has my limbs tied, and I'm twisted painfully into some sort of hogtie, my forearms stuck to my ankles."
"A bright light shines on me, almost blinding with how powerful it is."
"I can hear it droning on, a fluorescent buzz that tickles the nape of my neck."
"I hear some faint clopping sounds, along with the shifting of heavy boxes."
"I try to keep quiet as I look around, unsure of where I am, or who it is that's near me."
"While it's hard to see through the bright white light, I can make out stacks of boxes around me."
"Plastic bins, I think, like what Carl has in his crawlspace."
"Is that where I am?"
"I'm not sure because behind the bins are large, wooden beams, set against packed earth."
"It reminds me of the old mines I saw pictures of during my research."
"The ceiling is way too high to be the crawlspace as well."
"All the while, I can hear little giggles, whispers, and shushing sounds."
"There are patters of little feet underneath the louder clops."
"Slowly, I remember what had happened earlier; the splatters of blood, the footsteps behind me."
"I look up towards the sounds of the clopping and see the big form of a ram shifting boxes around, throwing lids aside."
"Carl?"
"It sort of looks like him, but he seems bigger, more shaggy."
"I shift my gaze to the darker corners of the room we're in and I gasp as I see a pair of eyes staring at me from the darkness."
"A little fox and what looks like a small grin below the eyes, just barely visible."
"The sounds of shifting bins stops and I hear the clopping coming closer to me."
c "\"You awake, boy?\""
"I flinch, but pretend to be asleep anyway, not moving until the ram suddenly crouches by my head causing me to cringe again."
"He feels around my body, checking the bindings before patting me on the face."
c "\"I know you are awake, but it does not matter now.\""
"The ram stands up and starts moving away."
m "\"W—wait!\""
"I wince, not really sure if that had been a good idea."
"Either way, he stops and turns back to me."
show Carlalttab Neutral with dissolve
"I look up at the ram, though it's hard with the way he's outlined in the incredibly bright light."
"It could actually be that light, but he definitely looks different, much bigger, his horns wider and more grown out."
c "\"What?\""
"His voice is different, too; deeper, more resonant."
"This isn't Carl anymore, but I guess I already know that."
m "\"I...what happened?\""
"My voice sounds tiny and weak in comparison to the big ram."
c "\"What do you mean 'what happened'?\""
hide Carlalttab with dissolve
"Carl...James sets back to moving around bins, opening lids, tossing stuff out."
m "\"Where's Raven, and Jenna?\""
c "\"You mean John?\""
"I don't say anything in response to that, still trying to look around."
"I keep catching glimpses of tiny feet and pairs of eyes just on the fringes of the dark nothingness."
"Their whispers and small giggles are a constant undertone."
show Carlalttab Neutral at center with dissolve
c "\"He's gone.\""
"I turn my attention back to the ram."
m "\"What do you mean?\""
c "\"I mean what I say, otter.\""
"I swallow my fear, trying to let the numbness of my ankle take over the rest of my body."
m "\"Where did she...he go?\""
show Carlalttab with dis
"James chuckles."
c "\"I don't know. I used the knife and—\""
show Carlalttab Neutral with dis
"The ram makes wiggly motions with his fingers above his horns."
show Carlalttab with dis
c "\"—gone.\""
"James shrugs his big shoulders."
m "\"...How?\""
show Carlalttab Neutral with dis
"The ram shakes his head again."
c "\"I know as much of this place as you, otter.\""
m "\"What about Raven?\""
c "\"Who?\""
m "\"The dog...the husky.\""
"Carl shrugs again."
c "\"Same thing.\""
hide Carlalttab with dissolve
"Silence drags on as the ram offers nothing else, turning back to his work."
"I work my hands around a bit, feeling a good deal of give in the bindings."
"They don't really feel like any sort of rope, though...more like clothes."
"I close my eyes, trying not to let the overpowering fear take over."
m "\"Carl? Carl, are you there?\""
"No response."
"Another giggle to my right draws my attention."
"I see another fox, even smaller than the first one."
"He dashes past the light, his figure blotting it out for just a moment."
"I hear a slap and then a snarl from James."
c "\"Little SHITS!\""
"I watch as the fox disappears into the darkness."
"I stare for a while before quietly venturing another question."
m "\"Who are they?\""
"Another pair of eyes dances around behind the light."
"James doesn't respond."
"I remember the newspaper clippings about the missing boys, the serial killer...."
c "\"Well, can't find all of them, but this is probably enough.\""
"I hear some rustling, then a huge jumble of thuds and clattering sounds as James dumps a bin onto the dirt-covered ground."
"The ram stomps off, disappearing behind the light."
"Things go quiet for a moment, aside from the distant clopping of the ram's footsteps."
"Then the whispering starts up again and I feel several pairs of eyes on me."
"First one, then two, then five tiny figures appear in front of the light."
"I can hear more behind me."
m "\"Wh-who are you...please.\""
"I try to cringe into a tight ball, but the bindings have me terribly exposed."
"They're dressed in old fashioned clothes; overalls, denim, and some are shirtless."
"Maybe it's Meseta."
m "\"What do you want?\""
"I close my eyes, waiting, wondering if maybe they'll kill me."
"It would probably be for the best."
"I'm tired, tired of this nightmare."
"Fingers start poking at my wrists."
m "\"H—hey...\""
"I try to jerk away, and as I do, my left hand slips out of the bindings."
"I pause, then a loud bang comes from toward the light and the small figures all disappear with a rush of wind."
c "\"Goddamn little shits...\""
"James mutters from behind the light."
"I hear the sound of sloshing liquid inside of a large container."
"As discreetly as I can, I start to try and work my other hand around, using my free one to loosen up the bindings."
"It's definitely clothes, and they're poorly tied together."
"The sloshing sounds get a bit louder as James steps in front of the floodlight."
"Then he tips the container he's holdings upside down, and I see a long nozzle, light shining through the translucent neck."
"I realize what it is as I hear liquid pattering onto the pile James has made."
"The smell of gasoline hits my nose as I start to panic."
m "\"Carl? Carl, wait, stop!\""
"My other hand pops free as I start to writhe around, but it's my legs that I need to get me out of here."
m "\"Carl? James, please, don't do this, can you let me go first?\""
"James moves away from the pile to pour the gas on the other bins."
m "\"Why are you doing this to me!?\""
"He flashes me a grin before continuing to splash gas onto all the bins, walking in a circle around me."
show Carlalttab Depressed at center with dissolve
c "\"Getting rid of evidence. You're part of the evidence.\""
"The whispers get more excited, the children running back and forth in front of the floodlight."
c "\"I would have stabbed you earlier but I lost it in that damn husky when I put it through his gut.\""
show Carlalttab Neutral with dis
"James glances back at me."
c "\"This is what happens when you meddle.\""
hide Carlalttab with dissolve
"Once Carl completes the circle of bins, he disappears behind the floodlight again."
"At that point, I start to pull at the bindings wildly, tugging at my ankles, internally screaming at every tug on my injury."
"This time the foxes don't approach, they just watch from the darkness."
m "\"Help...me...\""
"I sob through clenched teeth at them, but they don't move."
"I stop struggling, instead trying to feel through the bindings, tugging here and there, trying to loosen something."
"Finally I start to feel the knots shift a bit."
"My right leg comes free."
"The whispers crescendo, along with some giggling sounds."
"I hear James coming back and I try to keep twisted up in my feigned hogtie position."
"A glow appears in the darkness, and I see James step in front of the floodlight with a lighter in his hand."
show Carlalttab Neutral at center with dissolve
c "\"Sorry, otter, but I need to thank you and your friends for finally bringing this all to a close.\""
"The ram puts his free hand to his chest."
c "\"I really thought I would spend a lot longer worrying about this all getting out, but now—\""
show Carlalttab with dis
"He raises the lighter."
c "\"I can finally put this to an end."
stop music fadeout 5.0
hide Carlalttab with dissolve
"A small figure runs from behind the light and with a loud smack, the lighter goes flying."
"It's flung in my direction and, thankfully, it goes out as it flies through the air, then skitters on the dirt toward me."
"I drop the facade and uncurl, snatching the lighter up and struggling to stand."
"I'm just in time to see a huge ram charging me, his horns down, aimed straight at my chest."
"I jump to the side, but get clipped in the elbow, sending me and the lighter spinning through the air."
"James doesn't even go for me, instead disappearing into the dark after the lighter."
"I don't wait to see how it turns out, rushing toward the exit to the mine."
"I'm just a few feet away from the exit when I hear a huge whooshing sound and wind seems to rush from the exit, almost blowing me back."
stop loop fadeout 3.0
play sound "firestart.ogg"
play music "fire.ogg" fadein 3.0
scene bg fire with dissolve
"Breath is sucked from my lungs, and I go down to my knees, covering my head as it feels like all my fur is going to be burned off."
"I look behind me at the blinding fire."
m "\"Carl!\""
"I cover my mouth and nose, trying to breathe, but the heat beats me back like a physical force."
"And now, everything is real."
"I'm in the crawlspace, the massive beams are gone, the ceiling is lower, there's no more mine."
"I back up into the doorway, getting blasted with smoke."
m "\"CARL!\""
"I scream as loud as I can, all the while I'm still moving back."
"And then I see the familiar horns and Carl appears from the smoke and flames, singed, but alive."
"He charges at me, and I see the rage in his eyes."
"I might be back in the mansion, but Carl isn't..."
"I back away into the basement, out of the crawlspace, ducking low as smoke billows over me."
"It looks like Carl's coming after me, but just as he reaches out..."
"Little tiny paws grasp around his waist, his chest, and his face, pulling him back into the crawlspace."
"Carl reaches out, latching onto the door frame, snarling with rage."
"His eyes are wide, spittle flying from his mouth as he fights to pull himself from the grasp of the small foxes."
"I watch and only hesitate for a moment before I reach out to grasp one of Carl's hands."
"He may be possessed, he may have tried to kill me, but my friend is still in there somewhere"
"—And there's no way in hell I'll willingly let him burn to death."
"I lean back, pulling the ram as hard as I can, getting a face full of smoke as I stand to get some leverage."
"Carl, or James, grunts and growls, as if unsure of what to do."
"The little hands hold firm though, pulling back into the flaming pit behind the ram."
"I get weak, my lungs screaming in the smokey air, feeling my limbs start to give out—"
"And then something gives, but it's Carl."
"The hands pull through him, and something large and transparent gets pulled out."
"It flies back with a howl, and Carl flies forward into me, the door goes closed with a snap."
stop music fadeout 5.0
"I fall back with a crunch, my already hazy mind almost blacking out as the ram falls on top of me."

scene bg burningmansion with slow_dissolve

"The following events are a blur to me."
"I remember seeing Carl staring down at me, yelling my name."
"I remember a blind stumble through smoke."
"A dark basement, crumbling stairs, and two sets of bloody footprints through the kitchen and out into the night."
"We follow them."
"And then sitting in the desert, my head in Carl's lap."
"I watch his eyes glitter in the dancing firelight."
"His eyes are blank and far away."
"I reach up to touch his face, say thanks somehow."
"He doesn't look down."
"His eyes stay empty..."
scene bg black with slow_dissolve

###CREDITS###

play loop "echothemedark.ogg" fadein 3.0
###########################CREDITS###############################
window hide
show end with transition_fade
$ end = "carlb"

pause 2.0

scene bg black with slow_dissolve

call screen credits

scene bg black with dissolve
stop sound fadeout 3.0
$ renpy.pause(3.0, hard=False)

return

scene end with ending_fade
$ renpy.pause(5.0, hard=False)
